name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Adjust the branch to match your needs

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v1

      # Step 2: Log in to Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t yevhen625/pet_jar:latest .

      # Step 4: Push the image to Docker Hub
      - name: Push Docker image
        run: docker push yevhen625/pet_jar:latest
