name: Run JAR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-jar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        java-package: jdk

    - name: Build with Maven
      run: mvn clean package

    - name: Build Docker image
      run: docker build -t pets-app .

    - name: Run Docker container with port mapping
      run: docker run -d -p 80:8080 pets-app
