name: Run JAR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-jar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        java-package: jdk

    - name: Run JAR
      run: java -cp target/pets-0.0.1-SNAPSHOT.jar com.example.pets.PetsApplication
